import localFont from "next/font/local";
import "./globals.css";
import { Poppins } from "next/font/google"
import { AppSidebar } from "@/components/ui/app-sidebar";
import { SidebarTrigger,SidebarProvider } from "@/components/ui/sidebar";
import Navbar from "@/components/ui/navbar";
import AuthProvider from "@/components/ui/providers/AuthProvider";
import { Toaster } from "@/components/ui/toaster";


const poppins = Poppins({
  subsets: ['latin'],
  weight: '400'
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="dark">
      <body
        className={`${poppins.className} antialiased`}
      >
            <AuthProvider>
                <SidebarProvider>
                <AppSidebar />
                <main className="w-full">
                <SidebarTrigger />
                <Navbar />
                {children}
                <Toaster />
               </main>
             </SidebarProvider>
          </AuthProvider> 
      </body>
    </html>
  );
}
